### ISSUE TITLE
3rd parameter "MatchNo"?

### ISSUE THREAD

**Issue by Solarbotics** [darrenhewett/Excel-Regex#1]
Trying to pin down what this 3rd parameter does. Looking at your "test sheet.xlsx" I see it used in test 7 , 8, and 9, but I'm having issues divining its purpose. Can you point me in the right direction?

...oH.... For multiple matches. That's the number of the set matched in the Regex (if applicable). Ok. At least this is documented for anybody else looking for the answer!

Thx for a great utility!

**Comment by darrenhewett** [comment]
No worries, glad you figured it out!
